version: '3'

services:
  gym-api-db:
    container_name: gym-api-db
    ports:
      - 5432:5432
    image: bitnami/postgresql
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=gym-api-db
